- name: Set background picture
  ansible.builtin.command:
    cmd: osascript -e 'tell application "System Events" to tell every desktop to set picture to "{{ background_picture }}" as POSIX file'

- name: Disable sleep mode
  ansible.builtin.command:
    cmd: pmset -a sleep 0 hibernatemode 0 disablesleep 1
  become: true

- name: Remove recent items from Dock
  community.general.osx_defaults:
    domain: com.apple.dock.plist
    key: show-recents
    type: bool
    value: false
  notify:
    - Refresh Dock

- name: Show hidden files on Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: Allow custom location for Finder windows
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfLo

- name: Set Home folder as the default location for new Finder windows
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{ ansible_env.HOME }}"
  notify:
    - Refresh Finder

- name: Show all filename extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Allow text selection in Quick Look
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Display full POSIX path as Finder window title
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Display path in Finder status row
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Default arrange by kind
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXArrangeGroupViewBy
    type: string
    value: kind
  notify:
    - Refresh Finder

- name: Preferred arrange by kind
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredGroupBy
    type: string
    value: kind
  notify:
    - Refresh Finder

- name: Arrange by kind
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FK_ArrangeBy
    type: string
    value: kind
  notify:
    - Refresh Finder

- name: Sort folders first
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify:
    - Refresh Finder

- name: Use column view in all Finder windows by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
  notify:
    - Refresh Finder

- name: Set the icon size of Dock items
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 50
  notify:
    - Refresh Dock

- name: Enable the 'reduce transparency' option. Save GPU cycles.
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: reduceTransparency
    type: bool
    value: true

- name: Show the main window when launching Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

- name: Show all processes in Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0

- name: Disable screensaver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: 0
