- name: Configure global paths
  copy:
    dest: /etc/paths
    mode: 0644
    content: |
      /opt/homebrew/bin
      /usr/local/bin
      /usr/local/sbin
      /usr/bin
      /bin
      /usr/sbin
      /sbin
  become: true

- name: Ensure homebrew zsh is in allowed shells
  lineinfile:
    path: /etc/shells
    line: "{{ brew_bin }}/zsh"
  become: true

- name: Proove we connected with the given user
  shell: whoami
  register: whoami_result

- name: Set ZSH as the default shell
  shell: "chsh -s {{ brew_bin }}/zsh {{ whoami_result.stdout }}"
  become: true
