homebrew_installed_packages:
  - ansible
  - autoconf
  - bash-completion
  - colordiff
  - coreutils
  - curl
  - esolitos/ipa/sshpass
  - gabrie30/utils/ghorg
  - git
  - git-lfs
  - graphviz
  - go
  - gzip
  - jenv
  - jq
  - less
  - k6
  - mas
  - node@18
  - openssl
  - pkg-config
  - telnet
  - tree
  - watch
  - wget
  - yq
  - zsh
  - zsh-history-substring-search

homebrew_cask_apps:
  - adobe-acrobat-reader
  - airflow
  - authy
  - chrome-remote-desktop-host
  - cornercal
  - docker
  - google-chrome
  - hot
  - iterm2
  - jetbrains-toolbox
  - mucommander
  - mysides
  - openvpn-connect
  - plex
  - postman
  - redisinsight
  - qbittorrent
  - scroll-reverser
  - sequel-ace
  - shifty
  - skype
  - slack
  - stremio
  - sublime-text
  - telegram
  - vlc
  - vysor
  - whatsapp
  - zoom

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

mas_installed_apps:
  - id: 1352778147
    name: Bitwarden (1.30.0)

mas_email: false
mas_password: false
mas_signin_dialog: false

oh_my_zsh_plugins:
  - git
  - docker
  - zsh-history-substring-search

krew_plugins: [ ]

favourites:
  - name: Home
    path: ""
  - name: Workspace
    path: workspace

ssh_private_key: false
ssh_public_key: false

secret_profile: false

dotfiles:
  - src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  - src: .gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
  - src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  - src: ssh-config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
  - src: profile.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/profile.zsh"
  - src: iterm-profile.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/iterm-profile.json"
  - src: ghorg-conf.yaml
    dest: "{{ ansible_env.HOME }}/.config/ghorg/conf.yaml"
  - src: docker-config.json
    dest: "{{ ansible_env.HOME }}/.docker/config.json"

ghorg:
  - name: diboris
    scm: github
    cloneType: user
    path: "{{ ansible_env.HOME }}"
    outputDir: workspace/diboris
    baseUrl: https://api.github.com/

jenv_plugins: [ ]
