homebrew_installed_packages:
  - ansible
  - autoconf
  - bash-completion
  - colordiff
  - coreutils
  - curl
  - esolitos/ipa/sshpass
  - gabrie30/utils/ghorg
  - git
  - git-lfs
  - graphviz
  - go
  - gzip
  - jenv
  - jq
  - less
  - mas
  - node@18
  - openssl
  - pkg-config
  - telnet
  - tree
  - watch
  - wget
  - yq
  - zsh
  - zsh-history-substring-search

homebrew_cask_apps:
  - adobe-acrobat-reader
  - authy
  - chrome-remote-desktop-host
  - cornercal
  - docker
  - google-chrome
  - google-cloud-sdk
  - hot
  - hubstaff
  - iterm2
  - jetbrains-toolbox
  - mucommander
  - mysides
  - plex
  - postman
  - qbittorrent
  - scroll-reverser
  - shifty
  - skype
  - slack
  - stremio
  - sublime-text
  - telegram
  - temurin
  - temurin11
  - temurin17
  - vlc
  - whatsapp
  - zoom

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

mas_installed_apps:
  - id: 1352778147
    name: Bitwarden (1.30.0)
#  - id: 497799835
#    name: Xcode (13.2.1)

mas_email: false
mas_password: false
mas_signin_dialog: false

oh_my_zsh_plugins:
  - git
  - kubectl
  - docker
  - zsh-history-substring-search

krew_plugins: [ ]

favourites:
  - name: Home
    path: ""
  - name: Workspace
    path: workspace

ssh_private_key: false
ssh_public_key: false

secret_profile: false

dotfiles:
  - src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  - src: .gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
  - src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  - src: ssh-config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
  - src: profile.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/profile.zsh"
  - src: iterm-profile.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/iterm-profile.json"
  - src: ghorg-conf.yaml
    dest: "{{ ansible_env.HOME }}/.config/ghorg/conf.yaml"
  - src: docker-config.json
    dest: "{{ ansible_env.HOME }}/.docker/config.json"

ghorg:
  - name: diboris
    scm: github
    clone-type: user
    path: "{{ ansible_env.HOME }}"
    outputDir: diboris
    base-url: https://api.github.com/

jenv_plugins:
  - export
