- name: Clone macos-provisioner repo
  ansible.builtin.git:
    repo: git@github.com:slamdev/macos-provisioner.git
    dest: "{{ ansible_env.HOME }}/.macos-provisioner"
    accept_hostkey: yes

- name: Symlink sudoers
  file:
    src: "{{ ansible_env.HOME }}/.macos-provisioner/dotfiles/sudoers"
    dest: /private/etc/sudoers.d/custom
    state: link
    group: 0
    owner: 0
  become: yes

- name: Symlink files
  file:
    src: "{{ ansible_env.HOME }}/.macos-provisioner/dotfiles/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ dotfiles }}"

- name: Load secret data
  copy:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/secret-profile.zsh"
    mode: 0600
    content: "{{ secret_profile }}"
