- name: Get MAS account status
  command: "{{ brew_bin }}/mas account"
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  check_mode: false
  changed_when: false

- name: Sign in to MAS when email and password are provided.
  command: '{{ brew_bin }}/mas signin "{{ mas_email }}" "{{ mas_password }}"'
  register: mas_signin_result
  when:
    - mas_account_result.rc == 1
    - mas_email | bool
    - mas_password | bool
    - not mas_signin_dialog

- name: Sign in to MAS when email is provided, and complete password and 2FA using dialog.
  command: '{{ brew_bin }}/mas signin "{{ mas_email }}" "{{ mas_password }}" --dialog'
  register: mas_signin_result
  when:
    - mas_signin_dialog
    - mas_account_result.rc == 1
    - mas_email | bool

- name: List installed MAS apps.
  command: "{{ brew_bin }}/mas list"
  register: mas_list
  check_mode: false
  changed_when: false

- name: Ensure configured MAS apps are installed.
  command: '{{ brew_bin }}/mas install "{{ item.id|default(item) }}"'
  with_items: "{{ mas_installed_apps }}"
  when: (item.id | default(item) | string) not in mas_list.stdout
