- name: Check if rosetta is already installed.
  stat: "path=/Library/Apple/System/Library/Receipts/com.apple.pkg.RosettaUpdateAuto.bom"
  register: rosetta_file
  check_mode: false

- name: Install rosetta
  command: softwareupdate --install-rosetta --agree-to-license
  when: ansible_machine == 'arm64' and not rosetta_file.stat.exists
